{% set name = "spaghetti" %}
{% set version = "1.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9beddbb3bf285e88745d36aee886c78ac6e6a416f0f9b1a441265c8c08f923d

build:
  skip: true  # [py<310]
  number: 1
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools_scm >=6.2
    - toml
    - wheel
  run:
    - python
    - esda >=2.1
    - geopandas >=0.12
    - libpysal >=4.6
    - numpy >=1.22
    - pandas >=1.4,!=1.5.0
    - rtree >=1.0
    - scipy >=1.8
    - shapely >=2.0.1

test:
  source_files:
    - spaghetti/tests
  imports:
    - spaghetti
    - spaghetti.analysis
    - spaghetti.network
    - spaghetti.util
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv spaghetti/tests
  requires:
    - python
    - pip
    - pytest

about:
  home: https://pysal.org/spaghetti
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: SPAtial GrapHs - nETworks, Topology, & Inference
  description: |
    Spaghetti is an open-source Python library for the analysis
    of network-based spatial data. Originating from the network 
    module in [PySAL](https://pysal.org) (Python Spatial Analysis Library), 
    it is under active development for the inclusion of 
    newly-proposed methods for building graph-theoretic 
    networks and the analysis of network events.
  doc_url: https://pysal.org/spaghetti
  dev_url: https://github.com/pysal/spaghetti

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
